version: '3'
services:
  qinglong:
    image: whyour/qinglong:latest
    container_name: qinglong
    environment:
      - hostname=QL
      - name=QL
    volumes:
      - /mnt/disk/docker-volume/qinglong/config:/config
      - /mnt/disk/docker-volume/qinglong/log:/ql/log
      - /mnt/disk/docker-volume/qinglong/db:/ql/db
      - /mnt/disk/docker-volume/qinglong/scripts:/ql/scripts
      - /mnt/disk/docker-volume/qinglong/jbot:/ql/jbot
      - /mnt/disk/docker-volume/qinglong/raw:/ql/raw
      - /mnt/disk/docker-volume/qinglong/repo:/ql/repo
      - /mnt/disk/docker-volume/qinglong/oscript:/ql/oscript
    ports:
     - "5700:5700"
     - "5701:5701"
    restart: always
