version: '3'
services:
  qinglong:
    image: whyour/qinglong:latest
    container_name: qinglong
    environment:
      - hostname=QL
      - name=QL
    volumes:
      - ./disk/docker-volume/qinglong/config:/config
      - ./disk/docker-volume/qinglong/log:/ql/log
      - ./disk/docker-volume/qinglong/db:/ql/db
      - ./disk/docker-volume/qinglong/scripts:/ql/scripts
      - ./disk/docker-volume/qinglong/jbot:/ql/jbot
    ports:
     - "5700:5700"
     - "5701:5701"
    restart: always
