version: "3"
services:
  nginxWebUi-server:
    image: cym1102/nginxwebui:latest
    container_name: nginxwebui
    volumes:
      - /mnt/disk/docker-volume/nginxWebUI:/disk/nginxWebUI
    environment:
      - hostname=nginxwebui
      - name=nginxwebui
    ports:
      - "8080:8080"
    privileged: true
