version: '3.7'
services:
  elecv2p:
    image: elecv2/elecv2p
    container_name: elecv2p
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8100:80"
      - "8101:8001"
      - "8102:8002"
    volumes:
      - "/mnt/disk/docker-volume/elecv2p/JSFile:/usr/local/app/script/JSFile"
      - "/mnt/disk/docker-volume/elecv2p/Lists:/usr/local/app/script/Lists"
      - "/mnt/disk/docker-volume/mnt/disk/docker-volume/elecv2p/Store:/usr/local/app/script/Store"
      - "/mnt/disk/docker-volume/elecv2p/Shell:/usr/local/app/script/Shell"
      - "/mnt/disk/docker-volume/elecv2p/rootCA:/usr/local/app/rootCA"
      - "/mnt/disk/docker-volume/elecv2p/efss:/usr/local/app/efss"
