version: '3'
services:
  web:
    image: sicko1111/bilibili_upload_tool_web:latest
    ports:
      - 3000:3000
  api:
    image: sicko1111/bilibili_upload_tool_api:latest
    ports:
      - 9977:9090
    volumes:
      - ./env:/env/
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
