version: '3'
    
services:
  server:
    image: teddysun/kms
    container_name: kms
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    privileged: true
    ports:
      - "1688:1688"
