# docker-compose版本
version: '3'
# 服务
services:
# 服务名
  n1-media:
  # 镜像源地址
    image: taoskycn/n1-media-server:0.2
    # 容器名
    container_name: n1
    # 环境内部设置
    environment:
    # 主机名
      - hostname=n1
      - name=n1
    stdin_open: true
    tty: true
    # 卷
    volumes:
    # 系统内文件:Docker内文件
      - /mnt/disk/docker-volume/n1-media/exmedia:/media/exmedia
    # 系统内端口:docker内端口
    ports:
     - "1001-1006:1001-1006"
     - "51413:51413"
     - "548:548"
    restart: unless-stopped
    
