version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    network_mode: "host"
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /mnt/disk/docker-volume/data:/data
      - /mnt/disk/docker-volume/letsencrypt:/etc/letsencrypt
